title: "home"

#remote_theme: "mmistakes/minimal-mistakes"
#minimal_mistakes_skin: default
theme: jekyll-theme-hacker   # or any theme you choose

locale: en

markdown: kramdown
mathjax: true

plugins:
  - jekyll-seo-tag
  - jekyll-feed

navigation:
  main: main

plugins:
#- jekyll-remote-theme
#- jekyll-include-cache
- jekyll-seo-tag
- jekyll-feed
