title: "home"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: default

# Load the custom CSS file
custom_css:
- assets/css/auto-dark.scss

locale: en

markdown: kramdown
mathjax: true

navigation:
  main: main

enable_full_width: true

defaults:
- scope:
    path: ""
    type: "pages"
  values:
    sidebar: false

plugins:
- jekyll-remote-theme
- jekyll-include-cache
- jekyll-seo-tag
- jekyll-feed
