title: "Damiano's homepage"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: default
locale: en

markdown: kramdown
mathjax: true

navigation: main

plugins:
- jekyll-remote-theme
- jekyll-include-cache
- jekyll-seo-tag
- jekyll-feed
