#!/usr/bin/env python3
"""Self-check for scripts/slides.py against the real _data/talks.yml.

    python3 tests/test_slides.py

Also pins the content the hand-written /slides/ page used to carry, so the
generated page can't silently drop a slide PDF, video, note or entry.
"""
import re

import _helpers

# Every slide PDF the old hand-written page linked (relative names) — each must
# still be reachable from the generated page.
OLD_PDFS = [
    '2020_03_31_Versailles_Testa.pdf',
    '2020_12_08_WMS_Calculations.pdf',
    '2020_ToM_Testa.pdf',
    '2021_01_07_Testa_Lean_Together_2021.pdf',
    '2021_11_22_nMDS.pdf',
    '2021_11_29_lines_Alt.pdf',
    '2023_Pisa_Maths_Autom_Thm_Proving.pdf',
    '2025_Lean_Together_linter_talk.pdf',
    '2026_Machine_Verified_Reasoning.pdf',
    'AG.pdf',
    'Maintaining_1_Maths.pdf',
]


def main():
    S, entries = _helpers.load('slides')
    md = S.to_markdown(entries)

    assert md.startswith('---\n')
    assert 'math: true' in md.split('---', 2)[1]        # MathJax enabled
    assert 'GENERATED by scripts/slides.py' in md

    # One paragraph per DECK: tellings that share a `slides` URL are grouped
    # (web_only included), so the count is distinct URLs, not entries.
    slide_entries = [e for e in entries if e.get('slides')]
    n = len({e['slides'] for e in slide_entries})
    body = md.split('-->', 1)[1].strip()
    assert body.count('\n\n') == n - 1, 'one blank-line-separated paragraph per deck'

    # A deck used at several venues is listed once, with every venue present.
    conics = [e for e in slide_entries
              if e['slides'].endswith('2011_03_11_Cork_conics.pdf')]
    assert len(conics) > 1, 'expected the Cork deck to be shared across tellings'
    assert md.count('](https://adomani.github.io/slides/2011_03_11_Cork_conics.pdf)') == 1, \
        'a shared deck must be linked once, not once per telling'
    for e in conics:
        assert e['venue'].rstrip('.') in md, f'venue dropped from grouped deck: {e["venue"]}'

    # No LaTeX leaked: no raw \href{...} and no bare $...$ math left.
    assert '\\href{' not in md, 'unconverted \\href leaked into the page'
    assert not re.search(r'\$[^$]*\$', md), 'unconverted $...$ math leaked'

    # Every old slide PDF is still linked.
    for pdf in OLD_PDFS:
        assert pdf in md, f'slide PDF dropped from /slides/: {pdf}'

    # Videos, the expository note, math and accents survive the conversion.
    assert 'watch?v=734jMwgjkkM' in md and 'watch?v=jlJl0p7pm7M' in md
    assert '[Castravet-Tevelev](https://arxiv.org/abs/1311.7673)' in md
    assert '\\\\(\\mathfrak{A}_{2n}\\\\)' in md            # $...$ -> \\(...\\)
    assert 'Düsseldorf' in md and 'Géométrie' in md        # accents
    assert '[part 2](https://adomani.github.io/PreCFSG/Maintenance/Maintaining_2_AI.pdf)' in md
    # web_only entries appear here but must be absent from the CV talks list.
    assert 'Using computers to do maths for us!' in md

    print(f'PASS: slides.py renders {n} slide entries; all old content preserved')


if __name__ == '__main__':
    main()
