#!/usr/bin/env python3
"""Self-check for scripts/minicourses_page.py against the real data.

    python3 tests/test_minicourses_page.py
"""
import _helpers


def main():
    P, entries = _helpers.load('minicourses_page')
    homepages = _helpers.read(P.COLLABORATORS)
    md = P.to_markdown(entries, homepages)

    assert md.startswith('---\n')
    assert 'GENERATED by scripts/minicourses_page.py' in md

    # One paragraph per non-cv_only entry; cv_only is hidden from the website.
    shown = [m for m in entries if not m.get('cv_only')]
    body = md.split('-->', 1)[1].strip()
    assert body.count('\n\n') == len(shown) - 1
    assert any(m.get('cv_only') for m in entries), 'expected a cv_only entry to hide'
    assert 'CIMPA' not in md, 'cv_only entry must NOT appear on the website'

    # Titles: bold, linked when the entry has a url.
    assert '[**The classification of finite simple groups**](https://github.com/adomani/PreCFSG)' in md
    assert '**Minicorso Lean**' in md and '[**Minicorso Lean**]' not in md   # no url -> plain bold

    # Collaborators: linked when in the directory, plain otherwise.
    assert '[Martin Bright](https://www.boojum.org.uk/maths/)' in md
    assert 'with Riccardo Brasca, Filippo Nuccio' in md                      # not in directory

    # An extra parenthetical link (the 2008 programme).
    assert '([programme](2008_WarwickMinicourse.pdf))' in md

    print(f'PASS: minicourses_page.py renders {len(shown)} minicourses (of {len(entries)})')


if __name__ == '__main__':
    main()
