#!/usr/bin/env python3
"""Shared helpers for the CV / website generators.

Every generator computes an output string and hands it to `emit()`, which either
writes it, prints it, or (with `--check`) verifies an existing file is in sync.
`cli()` wraps the common "--out PATH / --check" command line so each generator's
`main` is a single call. See scripts/README.md and scripts/build.py.
"""
import argparse
import os
import sys

import yaml


def header(script, data):
    """The '% GENERATED ... do not edit.' banner the CV .tex fragments start with."""
    return f'% GENERATED by scripts/{script} from {data} -- do not edit.\n'


def load(path):
    """Parse a YAML data file (UTF-8)."""
    with open(path, encoding='utf-8') as fh:
        return yaml.safe_load(fh)


def emit(path, content, *, count=None, noun='entries', check=False):
    """Write `content` to `path` (stdout if path is None or '-').

    With check=True, compare against the file instead: return 0 if in sync, 1
    (with a message on stderr) if it is stale or missing.
    """
    if check:
        current = (open(path, encoding='utf-8').read()
                   if path and path != '-' and os.path.exists(path) else None)
        if current == content:
            print(f'OK: {path} is up to date')
            return 0
        sys.stderr.write(f'ERROR: {path} is stale; regenerate it.\n')
        return 1

    if path in (None, '-'):
        sys.stdout.write(content)
        return 0
    with open(path, 'w', encoding='utf-8') as fh:
        fh.write(content)
    tail = f' ({count} {noun})' if count is not None else ''
    print(f'Wrote {path}{tail}')
    return 0


def cli(render, *, noun='entries'):
    """Standard `--out PATH [--check]` entry point for a single-output generator.

    `render()` returns either the content string or a `(content, count)` tuple.
    """
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default='-', help="output path ('-' for stdout)")
    ap.add_argument('--check', action='store_true',
                    help='verify --out is in sync instead of writing')
    a = ap.parse_args()
    content, count = _unwrap(render())
    return emit(a.out, content, count=count, noun=noun, check=a.check)


def _unwrap(result):
    """Accept either `content` or `(content, count)` from a render()."""
    if isinstance(result, tuple):
        return result
    return result, None
