#!/usr/bin/env python3
"""Shared helpers for the CV / website generators.

Each generator exposes one function, `render() -> str`; scripts/build.py is the
single entry point that materialises them all (and `emit()` writes, prints, or
--checks one output). See scripts/README.md and scripts/build.py.
"""
import os
import re
import sys

import yaml


def header(script, data):
    """The '% GENERATED ... do not edit.' banner the CV .tex fragments start with."""
    return f'% GENERATED by scripts/{script} from {data} -- do not edit.\n'


def load(path):
    """Parse a YAML data file (UTF-8)."""
    with open(path, encoding='utf-8') as fh:
        return yaml.safe_load(fh)


# --- Inline rich text -------------------------------------------------------
# Data fields hold neutral Markdown ([t](u), *em*, $math$, Unicode letters). The
# CV and the website each convert it to their own dialect; this is the whole of
# the "define the format once, small variations per target" idea.

_LINK = re.compile(r'\[([^\]]+)\]\(([^)]+)\)')      # [label](url)


def _split_math(s):
    """Split on $...$ spans: even indices are prose, odd indices are math."""
    return re.split(r'(\$[^$]*\$)', s)


def md_to_tex(s):
    """Markdown inline text -> LaTeX, for the CV.

    [t](u) -> \\href{u}{t}, *x* -> \\emph{x}, “ ” -> `` '', and &%#~ escaped.
    $...$ math and Unicode letters pass through unchanged (the CV reads UTF-8).
    """
    out = []
    for i, part in enumerate(_split_math(s)):
        if i % 2:                                   # a $...$ span: verbatim
            out.append(part)
            continue
        part = _LINK.sub(lambda m: '\\href{' + m.group(2) + '}{' + m.group(1) + '}', part)
        part = re.sub(r'\*([^*]+)\*', r'\\emph{\1}', part)
        for a, b in (('&', r'\&'), ('%', r'\%'), ('#', r'\#'),
                     ('~', r'\textasciitilde ')):
            part = part.replace(a, b)
        part = part.replace('“', '``').replace('”', "''")
        out.append(part)
    return ''.join(out)


def md_to_web(s):
    """Markdown inline text -> the site's kramdown. Only math differs: $x$ ->
    \\(x\\) (double backslash in the .md source survives kramdown to MathJax)."""
    return re.sub(r'\$([^$]*)\$', lambda m: '\\\\(' + m.group(1) + '\\\\)', s)


def itemize(banner, items, lead=''):
    """Wrap already-rendered item bodies in the CV's standard itemize envelope.

    `banner` is the `% GENERATED ...` header line (see `header()`); `lead` is any
    text between it and \\begin{itemize} (e.g. a bold subsection heading);
    `items` is the '\\n'-joined item bodies.
    """
    return banner + lead + '\\begin{itemize}\n' + items + '\n\\end{itemize}\n'


def emit(path, content, *, check=False):
    """Write `content` to `path` (stdout if path is None or '-').

    With check=True, compare against the file instead: return 0 if in sync, 1
    (with a message on stderr) if it is stale or missing.
    """
    if check:
        current = None
        if path and path != '-' and os.path.exists(path):
            with open(path, encoding='utf-8') as fh:
                current = fh.read()
        if current == content:
            print(f'OK: {path} is up to date')
            return 0
        sys.stderr.write(f'ERROR: {path} is stale; regenerate it.\n')
        return 1

    if path in (None, '-'):
        sys.stdout.write(content)
        return 0
    with open(path, 'w', encoding='utf-8') as fh:
        fh.write(content)
    print(f'Wrote {path}')
    return 0
