#!/usr/bin/env python3
"""Convert a BibTeX file into _data/publications.yml for the Jekyll site.

This is the shared-dataset prototype: `papers.bib` is the single source of
truth (biblatex renders the CV from it; this script renders the website's
publication data from the same file).

Usage:
    python3 scripts/bib2yaml.py _bibliography/papers.bib _data/publications.yml
"""
import re
import sys
import yaml

# --- tiny BibTeX parser -----------------------------------------------------
# Handles `@type{key, Field = {value} or "value" or bareword, ...}` with
# balanced braces in values. Good enough for this hand-maintained file.

def parse_bib(text):
    entries = []
    i, n = 0, len(text)
    while i < n:
        at = text.find('@', i)
        if at == -1:
            break
        brace = text.find('{', at)
        etype = text[at + 1:brace].strip().lower()
        # read balanced body
        depth, j = 0, brace
        while j < n:
            if text[j] == '{':
                depth += 1
            elif text[j] == '}':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        body = text[brace + 1:j]
        i = j + 1
        # key is up to first comma
        comma = body.find(',')
        key = body[:comma].strip()
        fields = parse_fields(body[comma + 1:])
        fields['__type__'] = etype
        fields['__key__'] = key
        entries.append(fields)
    return entries


def parse_fields(s):
    fields, i, n = {}, 0, len(s)
    while i < n:
        eq = s.find('=', i)
        if eq == -1:
            break
        name = s[i:eq].strip().lower()
        i = eq + 1
        while i < n and s[i] in ' \t\r\n':
            i += 1
        if i >= n:
            break
        if s[i] == '{':
            depth, j = 0, i
            while j < n:
                if s[j] == '{':
                    depth += 1
                elif s[j] == '}':
                    depth -= 1
                    if depth == 0:
                        break
                j += 1
            val = s[i + 1:j]
            i = j + 1
        elif s[i] == '"':
            j = i + 1
            while j < n and s[j] != '"':
                j += 1
            val = s[i + 1:j]
            i = j + 1
        else:  # bareword / number
            j = i
            while j < n and s[j] != ',':
                j += 1
            val = s[i:j].strip()
            i = j
        # advance past trailing comma
        nxt = s.find(',', i)
        i = nxt + 1 if nxt != -1 else n
        if name:
            fields[name] = ' '.join(val.split())
    return fields


# --- LaTeX -> display text ---------------------------------------------------
# papers.bib stores accents as UTF-8, so all that remains is stripping
# capitalization-protection braces ({F}ermat) and a couple of escapes, while
# leaving inline $...$ math untouched for MathJax.
def delatex(s):
    if not s:
        return s
    math = []
    def stash(m):
        math.append(m.group(0))
        return f'\x00{len(math)-1}\x00'
    s = re.sub(r'\$[^$]*\$', stash, s)          # protect math
    s = s.replace('{', '').replace('}', '')      # drop {F}ermat-style braces
    s = s.replace('\\&', '&').replace('~', ' ')
    s = re.sub(r'\s+', ' ', s).strip()
    s = re.sub('\x00(\\d+)\x00', lambda m: math[int(m.group(1))], s)
    return s


def format_authors(raw):
    out = []
    for name in re.split(r'\s+and\s+', raw.strip()):
        name = name.strip()
        if ',' in name:
            fam, giv = [p.strip() for p in name.split(',', 1)]
            name = f'{giv} {fam}'.strip()
        out.append(delatex(name))
    return out


CATEGORY = {  # keyword -> section bucket
    'published': 'publications', 'accepted': 'publications',
    'preprint': 'preprints', 'book': 'books',
}


def link_for(f):
    if f.get('doi'):
        return 'https://doi.org/' + f['doi']
    if f.get('url'):
        return f['url']
    ep = f.get('eprint', '')
    m = re.search(r'(\d{4}\.\d{4,5})', ep)
    if m:
        return 'https://arxiv.org/abs/' + m.group(1)
    return None


def to_record(f):
    venue = delatex(f.get('fjournal') or f.get('journal') or f.get('booktitle') or '')
    rec = {
        'key': f['__key__'],
        'title': delatex(f.get('title', '')),
        'authors': format_authors(f.get('author', '')),
        'year': f.get('year', ''),
    }
    if venue:
        rec['venue'] = venue
    for k in ('volume', 'number', 'pages'):
        if f.get(k):
            rec[k] = delatex(f[k])
    link = link_for(f)
    if link:
        rec['url'] = link
    kw = (f.get('keywords') or '').strip().lower()
    rec['category'] = CATEGORY.get(kw, 'publications')
    rec['status'] = kw
    return rec


HEADER = ('# GENERATED by scripts/bib2yaml.py from _bibliography/papers.bib\n'
          '# Do not edit by hand; edit the .bib and re-run the script.\n')


def render_yaml(bib_text):
    """Pure function: BibTeX text -> the publications.yml file contents."""
    records = [to_record(e) for e in parse_bib(bib_text)]

    def sort_key(r):
        y = re.sub(r'[^0-9]', '', r['year']) or '0'
        return -int(y)
    buckets = {'publications': [], 'preprints': [], 'books': []}
    for r in sorted(records, key=sort_key):
        buckets[r['category']].append(r)
    body = yaml.safe_dump(buckets, allow_unicode=True, sort_keys=False,
                          default_flow_style=False, width=100)
    return HEADER + body, buckets


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('-')]
    check = '--check' in sys.argv
    src, dst = args[0], args[1]
    with open(src, encoding='utf-8') as fh:
        out, buckets = render_yaml(fh.read())

    if check:
        # Golden-file test: does the committed dst match freshly generated output?
        try:
            current = open(dst, encoding='utf-8').read()
        except FileNotFoundError:
            current = None
        if current == out:
            print(f'OK: {dst} is up to date with {src}')
            return 0
        sys.stderr.write(
            f'ERROR: {dst} is stale. Regenerate with:\n'
            f'    python3 scripts/bib2yaml.py {src} {dst}\n')
        return 1

    with open(dst, 'w', encoding='utf-8') as fh:
        fh.write(out)
    n = sum(len(v) for v in buckets.values())
    print(f'Wrote {n} records to {dst} '
          f"(publications={len(buckets['publications'])}, "
          f"preprints={len(buckets['preprints'])}, books={len(buckets['books'])})")
    return 0


if __name__ == '__main__':
    sys.exit(main())
