#!/usr/bin/env python3
"""Generate the CV's "Organized conferences" list from _data/conferences.yml.

    python3 scripts/conferences.py --tex cv/sections/conferences_generated.tex
    python3 scripts/conferences.py --check      # verify the .tex is in sync

The four entries are heterogeneous (an \\href session title, plain \\emph
titles, differing "with ... venue ... dates" phrasing), so each is stored as one
verbatim `text` line and emitted as-is -- the same approach as the irregular
talks entries. One source, rendered into the CV; see scripts/README.md.
"""
import argparse
import sys

import yaml

DATA = '_data/conferences.yml'
HEADER = '% GENERATED by scripts/conferences.py from ' + DATA + ' -- do not edit.\n'
HEADING = '{\\textbf{Organized conferences}}'


def to_tex(entries):
    items = '\n'.join('\\item\n' + e['text'] for e in entries)
    return (HEADER + HEADING + '\n\\begin{itemize}\n' + items
            + '\n\\end{itemize}\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--tex', help='write the generated .tex to this path')
    ap.add_argument('--check', action='store_true',
                    help='verify --tex target is in sync (exit 1 if not)')
    args = ap.parse_args()

    entries = yaml.safe_load(open(DATA, encoding='utf-8'))
    tex = to_tex(entries)

    if args.check:
        if not args.tex:
            ap.error('--check requires --tex')
        current = open(args.tex, encoding='utf-8').read()
        if current != tex:
            print(f'OUT OF SYNC: {args.tex} does not match {DATA}', file=sys.stderr)
            sys.exit(1)
        print(f'{args.tex} is up to date with {DATA}')
        return

    if args.tex:
        with open(args.tex, 'w', encoding='utf-8') as f:
            f.write(tex)
        print(f'wrote {args.tex} ({len(entries)} conferences)')
    else:
        sys.stdout.write(tex)


if __name__ == '__main__':
    main()
