#!/usr/bin/env python3
"""Generate the website /minicourses/ page from _data/minicourses.yml — the same
source the CV uses (scripts/cv_sections.py). This retires the old Liquid loop, so
the page and the CV share one builder.

    python3 scripts/minicourses_page.py --out minicourses/index.md
    python3 scripts/minicourses_page.py            # stdout

Each non-`cv_only` entry becomes one Markdown paragraph:

    {year}, {date}, [**title**](url), {context}, with {people}, {venue} ([label](url)).

`url`, `context`, `collaborators` and `links` are optional; collaborators are
linked via _data/collaborators.yml (the single point of entry).
"""
import _common

DATA = '_data/minicourses.yml'
COLLABORATORS = '_data/collaborators.yml'

FRONT_MATTER = (
    '---\n'
    'title: Minicourses\n'
    'layout: single\n'
    '---\n'
    '\n'
    '<!-- GENERATED by scripts/minicourses_page.py from ' + DATA + ' -- do not edit. -->\n'
)


def _people(names, homepages):
    return ', '.join(f'[{n}]({homepages[n]})' if n in homepages else n for n in names)


def entry_md(m, homepages):
    title = f"[**{m['title']}**]({m['url']})" if m.get('url') else f"**{m['title']}**"
    line = f"{m['year']}, {m['date']}, {title}"
    if m.get('context'):
        line += f", {m['context']}"
    if m.get('collaborators'):
        line += f", with {_people(m['collaborators'], homepages)}"
    line += f", {m['venue']}"
    for link in m.get('links', []):
        line += f" ([{link['label']}]({link['url']}))"
    return line + '.'


def to_markdown(entries, homepages):
    shown = [m for m in entries if not m.get('cv_only')]      # cv_only hidden here
    body = '\n\n'.join(entry_md(m, homepages) for m in shown)
    return FRONT_MATTER + '\n' + body + '\n'


def render():
    entries = _common.load(DATA)
    homepages = _common.load(COLLABORATORS)
    n = sum(1 for m in entries if not m.get('cv_only'))
    return to_markdown(entries, homepages), n


if __name__ == '__main__':
    raise SystemExit(_common.cli(render, noun='minicourses'))
