#!/usr/bin/env python3
"""Generate the CV's Minicourses LaTeX block from the shared data file.

    _data/minicourses.yml   (canonical; also read directly by the website)
        └── scripts/minicourses.py --tex ─▶ a LaTeX itemize for the CV

The website renders the same YAML itself (Jekyll), so both the CV and the
website page come from one source. `url` and `links` are website-only (the CV
lists minicourses as plain text, matching its existing style).

    python3 scripts/minicourses.py --tex cv/sections/minicourses_generated.tex
    add --check to compare against an existing file instead of writing.
"""
import argparse
import os
import sys

import yaml

DATA = '_data/minicourses.yml'
HEADER = '% GENERATED by scripts/minicourses.py from ' + DATA + ' -- do not edit.\n'


def tex_escape(s):
    for a, b in (('\\', r'\textbackslash '), ('&', r'\&'), ('%', r'\%'),
                 ('#', r'\#'), ('_', r'\_'), ('~', r'\textasciitilde ')):
        s = s.replace(a, b)
    return s


def join_people(names):
    names = [tex_escape(n) for n in names]
    if len(names) == 1:
        return names[0]
    if len(names) == 2:
        return f'{names[0]} and {names[1]}'
    return ', '.join(names[:-1]) + ', and ' + names[-1]


def render_item(e):
    parts = [f"{e['year']}, {tex_escape(str(e['date']))}",
             r'{\emph{' + tex_escape(e['title']) + '}}']
    if e.get('context'):
        parts.append(tex_escape(e['context']))
    if e.get('collaborators'):
        parts.append('with ' + join_people(e['collaborators']))
    parts.append(tex_escape(e['venue']))
    return '\\item\n' + ', '.join(parts) + '.'


def to_tex(entries):
    items = '\n'.join(render_item(e) for e in entries)
    return (HEADER + '{\\textbf{Minicourses}}\n\\begin{itemize}\n'
            + items + '\n\\end{itemize}\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--tex', default='-')
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    with open(DATA, encoding='utf-8') as fh:
        entries = yaml.safe_load(fh)
    out = to_tex(entries)

    if a.check:
        cur = open(a.tex, encoding='utf-8').read() if os.path.exists(a.tex) else None
        if cur == out:
            print(f'OK: {a.tex} is up to date with {DATA}')
            return 0
        sys.stderr.write(f'ERROR: {a.tex} is stale; regenerate with '
                         f'scripts/minicourses.py --tex {a.tex}\n')
        return 1

    if a.tex == '-':
        sys.stdout.write(out)
    else:
        with open(a.tex, 'w', encoding='utf-8') as fh:
            fh.write(out)
        print(f'Wrote {a.tex} ({len(entries)} minicourses)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
