#!/usr/bin/env python3
"""Generate the publication outputs from the canonical JSON.

    _bibliography/publications.json   (canonical, hand-editable, has descriptions)
        ├── --yaml -> _data/publications.yml   (render-ready, for the website)
        └── --bib  -> _bibliography/papers.bib  (reconstructed, for the CV)

Usage:
Both outputs are materialised by scripts/build.py (the single entry point); this
module exposes `load()`, `to_yaml()` and `to_bib()`.
"""
import json
import os
import re
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bib2yaml as B  # reuse delatex/format_authors/to_record/link_for/CATEGORY

CANONICAL = '_bibliography/publications.json'
YAML_HEADER = ('# GENERATED by scripts/publications.py from '
               + CANONICAL + '\n# Do not edit by hand; edit the JSON and re-run.\n')
BIB_HEADER = ('@Comment{GENERATED by scripts/publications.py from '
              + CANONICAL + ' -- do not edit by hand.}\n\n')


def load():
    with open(CANONICAL, encoding='utf-8') as fh:
        return json.load(fh)


# --- JSON entry -> render record (reusing the display logic in bib2yaml) -----
def render_record(e):
    f = dict(e['fields'])
    f['__key__'] = e['key']
    f['__type__'] = e['type']
    f['author'] = ' and '.join(e.get('author', []))
    f['keywords'] = e.get('keywords', '')
    rec = B.to_record(f)
    if e.get('description'):
        rec['description'] = e['description']
    if e.get('citation_note'):
        rec['citation_note'] = e['citation_note']
    return rec


# Emit multi-line strings as `|` literal blocks (readable, no quoting/escaping);
# single-line strings keep the default style. Scoped to a private dumper so we
# don't mutate PyYAML's global SafeDumper.
class _BlockDumper(yaml.SafeDumper):
    pass


def _str_representer(dumper, data):
    style = '|' if '\n' in data else None
    return dumper.represent_scalar('tag:yaml.org,2002:str', data, style=style)


_BlockDumper.add_representer(str, _str_representer)


def to_yaml(entries):
    def year_key(r):
        return -int(re.sub(r'[^0-9]', '', r['year']) or '0')
    buckets = {'publications': [], 'preprints': [], 'books': []}
    for r in sorted((render_record(e) for e in entries), key=year_key):
        buckets[r['category']].append(r)
    return YAML_HEADER + yaml.dump(buckets, Dumper=_BlockDumper, allow_unicode=True,
                                   sort_keys=False, default_flow_style=False,
                                   width=100)


# --- JSON entry -> BibTeX (reconstruct; description is website-only) ----------
def to_bib(entries):
    def emit(e):
        preprint = 'preprint' in (e.get('keywords') or '').lower()
        lines = [f"@{e['type']}{{{e['key']},"]
        if e.get('author'):
            lines.append("  author = {" + ' and '.join(e['author']) + "},")
        for k in sorted(e['fields']):
            v = e['fields'][k]
            # The CV's biblatex runs url=false, so a plain `url` field is hidden.
            # For preprints the link is the only locator, so wrap it in
            # `howpublished = {\url{...}}`, which url=false does not suppress.
            if k == 'url' and preprint:
                lines.append(f"  howpublished = {{\\url{{{v}}}}},")
            else:
                lines.append(f"  {k} = {{{v}}},")
        if e.get('keywords'):
            lines.append(f"  keywords = {{{e['keywords']}}},")
        lines.append("}")
        return "\n".join(lines)
    return BIB_HEADER + "\n\n".join(emit(e) for e in entries) + "\n"
