#!/usr/bin/env python3
"""Generate the publication outputs from the canonical JSON.

    _bibliography/publications.json   (canonical, hand-editable, has descriptions)
        ├── --yaml -> _data/publications.yml   (render-ready, for the website)
        └── --bib  -> _bibliography/papers.bib  (reconstructed, for the CV)

Usage:
    python3 scripts/publications.py --yaml _data/publications.yml
    python3 scripts/publications.py --bib  _bibliography/papers.bib
    add --check to compare against the committed file instead of writing.
"""
import argparse
import json
import os
import re
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bib2yaml as B  # reuse delatex/format_authors/to_record/link_for/CATEGORY

CANONICAL = '_bibliography/publications.json'
YAML_HEADER = ('# GENERATED by scripts/publications.py from '
               + CANONICAL + '\n# Do not edit by hand; edit the JSON and re-run.\n')
BIB_HEADER = ('@Comment{GENERATED by scripts/publications.py from '
              + CANONICAL + ' -- do not edit by hand.}\n\n')


def load():
    with open(CANONICAL, encoding='utf-8') as fh:
        return json.load(fh)


# --- JSON entry -> render record (reusing the display logic in bib2yaml) -----
def render_record(e):
    f = dict(e['fields'])
    f['__key__'] = e['key']
    f['__type__'] = e['type']
    f['author'] = ' and '.join(e.get('author', []))
    f['keywords'] = e.get('keywords', '')
    rec = B.to_record(f)
    if e.get('description'):
        rec['description'] = e['description']
    if e.get('citation_note'):
        rec['citation_note'] = e['citation_note']
    return rec


def to_yaml(entries):
    def year_key(r):
        return -int(re.sub(r'[^0-9]', '', r['year']) or '0')
    buckets = {'publications': [], 'preprints': [], 'books': []}
    for r in sorted((render_record(e) for e in entries), key=year_key):
        buckets[r['category']].append(r)
    return YAML_HEADER + yaml.safe_dump(buckets, allow_unicode=True,
                                        sort_keys=False, default_flow_style=False,
                                        width=100)


# --- JSON entry -> BibTeX (reconstruct; description is website-only) ----------
def to_bib(entries):
    def emit(e):
        lines = [f"@{e['type']}{{{e['key']},"]
        if e.get('author'):
            lines.append("  author = {" + ' and '.join(e['author']) + "},")
        for k in sorted(e['fields']):
            lines.append(f"  {k} = {{{e['fields'][k]}}},")
        if e.get('keywords'):
            lines.append(f"  keywords = {{{e['keywords']}}},")
        lines.append("}")
        return "\n".join(lines)
    return BIB_HEADER + "\n\n".join(emit(e) for e in entries) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--yaml')
    ap.add_argument('--bib')
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    entries = load()
    target, out = (a.yaml, to_yaml(entries)) if a.yaml else (a.bib, to_bib(entries))
    if not target:
        ap.error('specify --yaml or --bib')

    if a.check:
        current = open(target, encoding='utf-8').read() if os.path.exists(target) else None
        if current == out:
            print(f'OK: {target} is up to date with {CANONICAL}')
            return 0
        sys.stderr.write(f'ERROR: {target} is stale. Regenerate with:\n'
                         f'    python3 scripts/publications.py '
                         f'{"--yaml" if a.yaml else "--bib"} {target}\n')
        return 1

    with open(target, 'w', encoding='utf-8') as fh:
        fh.write(out)
    print(f'Wrote {target} ({len(entries)} entries)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
