#!/usr/bin/env python3
"""Generate the website /slides/ page from the shared talk data.

    _data/talks.yml  (canonical)
        └── scripts/slides.py --out slides/index.md ─▶ the /slides/ page

The page lists every talk that carries a `slides` URL (newest first, in file
order), including `web_only` talks that are not in the CV. Fields authored for
the CV are LaTeX; this converts them to the kramdown/MathJax the site expects:

  \\href{u}{t}  ->  [t](u)
  $...$         ->  \\(...\\)      (double backslash survives kramdown to MathJax)
  \\&, accents, ``...''  ->  Unicode

    python3 scripts/slides.py --out slides/index.md
    python3 scripts/slides.py            # write to stdout
"""
import argparse
import re
import sys

import yaml

DATA = '_data/talks.yml'

FRONT_MATTER = (
    '---\n'
    'title: Slides\n'
    'layout: single\n'
    'math: true\n'
    '---\n'
    '\n'
    '<!-- GENERATED by scripts/slides.py from ' + DATA + ' -- do not edit. -->\n'
)

# LaTeX accents / escapes that occur in the talk fields, mapped to Unicode.
ACCENTS = [
    ('\\&', '&'),
    ('\\"u', 'ü'), ('\\"o', 'ö'), ('\\"a', 'ä'),
    ("\\'e", 'é'), ("\\'o", 'ó'), ("\\'a", 'á'),
    ('\\`e', 'è'), ('\\`a', 'à'),
    ('\\^o', 'ô'), ('\\^e', 'ê'),
    ('\\c{c}', 'ç'),
]


def web(s):
    """Convert a CV/LaTeX field to the markdown the /slides/ page uses."""
    # \href{url}{text} -> [text](url)
    s = re.sub(r'\\href\{([^{}]*)\}\{([^{}]*)\}', r'[\2](\1)', s)
    # $...$ -> \\(...\\)  (literal double backslash in the .md source)
    s = re.sub(r'\$([^$]*)\$', lambda m: '\\\\(' + m.group(1) + '\\\\)', s)
    # LaTeX quotes ``...'' -> “...”
    s = s.replace('``', '“').replace("''", '”')
    for a, b in ACCENTS:
        s = s.replace(a, b)
    return s


_MONTH_DAY = re.compile(r'^([A-Z][a-z]+) (\d{1,2})$')


def ordinal(n):
    suf = 'th' if 11 <= n % 100 <= 13 else {1: 'st', 2: 'nd', 3: 'rd'}.get(n % 10, 'th')
    return f'{n}{suf}'


def fmt_date(entry):
    """"February 12" + 2026 -> "February 12th, 2026"; ranges/absent handled."""
    date = entry.get('date')
    year = entry['year']
    if not date:
        return None
    m = _MONTH_DAY.match(str(date))
    if m:
        return f'{m.group(1)} {ordinal(int(m.group(2)))}, {year}'
    return f'{date}, {year}'          # e.g. "March 16-20, 2026"


def render(entry):
    title = web(entry['title'])
    parts = [f"[{title}]({entry['slides']})", web(entry['venue']).rstrip('.')]
    if entry.get('video'):
        parts.append(f"[video]({entry['video']})")
    line = ', '.join(parts)
    date = fmt_date(entry)
    line += f', {date}.' if date else '.'
    if entry.get('note'):
        line += ' ' + web(entry['note'])
    return line


def to_markdown(entries):
    talks = [e for e in entries if e.get('slides')]
    body = '\n\n'.join(render(e) for e in talks)
    return FRONT_MATTER + '\n' + body + '\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default='-', help='write the page here (default stdout)')
    a = ap.parse_args()
    entries = yaml.safe_load(open(DATA, encoding='utf-8'))
    md = to_markdown(entries)
    if a.out == '-':
        sys.stdout.write(md)
    else:
        with open(a.out, 'w', encoding='utf-8') as fh:
            fh.write(md)
        n = sum(1 for e in entries if e.get('slides'))
        print(f'Wrote {a.out} ({n} slide entries)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
