#!/usr/bin/env python3
"""Generate the website /slides/ page from the shared talk data.

    _data/talks.yml  (canonical)
        └── scripts/slides.py ─▶ slides/index.md  (the /slides/ page)

The page lists every talk that carries a `slides` URL (newest first, in file
order), including `web_only` talks that are not in the CV. Fields authored for
the CV are LaTeX; this converts them to the kramdown/MathJax the site expects:

  \\href{u}{t}  ->  [t](u)
  $...$         ->  \\(...\\)      (double backslash survives kramdown to MathJax)
  \\&, accents, ``...''  ->  Unicode

The same deck given at several venues is ONE entry here (the venues are listed
after the title), even though each telling is its own line in the CV: entries
that share a `slides` URL are grouped. The URL is the identity — two different
decks with the same title (e.g. two versions of one talk) stay separate.

scripts/build.py writes this; preview it with `python3 scripts/build.py slides`.
"""
import collections
import re

import _common

DATA = '_data/talks.yml'

FRONT_MATTER = (
    '---\n'
    'title: Slides\n'
    'layout: single\n'
    'math: true\n'
    '---\n'
    '\n'
    '<!-- GENERATED by scripts/slides.py from ' + DATA + ' -- do not edit. -->\n'
)

web = _common.md_to_web          # fields are Markdown; only $math$ needs converting


_MONTH_DAY = re.compile(r'^([A-Z][a-z]+) (\d{1,2})$')


def ordinal(n):
    suf = 'th' if 11 <= n % 100 <= 13 else {1: 'st', 2: 'nd', 3: 'rd'}.get(n % 10, 'th')
    return f'{n}{suf}'


def fmt_date(entry):
    """"February 12" + 2026 -> "February 12th, 2026"; ranges/bare-month/absent handled."""
    date = entry.get('date')
    year = entry['year']
    if not date:
        return None
    m = _MONTH_DAY.match(str(date))
    if m:
        return f'{m.group(1)} {ordinal(int(m.group(2)))}, {year}'
    if not any(c.isdigit() for c in str(date)):
        return f'{date} {year}'       # bare month, e.g. "October 2011" (no comma)
    return f'{date}, {year}'          # a day range, e.g. "March 16-20, 2026"


def render_entry(entry):
    title = web(entry['title'])
    parts = [f"[{title}]({entry['slides']})", web(entry['venue']).rstrip('.')]
    if entry.get('video'):
        parts.append(f"[video]({entry['video']})")
    line = ', '.join(parts)
    date = fmt_date(entry)
    line += f', {date}.' if date else '.'
    if entry.get('note'):
        line += ' ' + web(entry['note'])
    return line


def _venue_date(entry):
    """"venue (date)" for one telling, with an inline [video] if it was recorded."""
    s = web(entry['venue']).rstrip('.')
    if entry.get('video'):
        s += f", [video]({entry['video']})"
    date = fmt_date(entry)
    return f'{s} ({date})' if date else s


def render_group(group):
    """One paragraph per deck. A single telling keeps the original one-line form;
    a deck given at several venues names the title once and lists the venues (and
    their dates), so it is not repeated verbatim. Any `note`s follow at the end."""
    if len(group) == 1:
        return render_entry(group[0])
    first = group[0]
    line = f"[{web(first['title'])}]({first['slides']}), given at " \
           + '; '.join(_venue_date(e) for e in group) + '.'
    notes = [web(e['note']) for e in group if e.get('note')]
    if notes:
        line += ' ' + ' '.join(notes)
    return line


def to_markdown(entries):
    # Group talks that share a deck (`slides` URL), keeping first-appearance
    # (newest-first) order; each group renders as one paragraph.
    groups = collections.OrderedDict()
    for e in entries:
        if e.get('slides'):
            groups.setdefault(e['slides'], []).append(e)
    body = '\n\n'.join(render_group(g) for g in groups.values())
    return FRONT_MATTER + '\n' + body + '\n'


def render():
    return to_markdown(_common.load(DATA))
