#!/usr/bin/env python3
"""Generate the CV's "Talks and conferences" LaTeX list from the shared data.

    _data/talks.yml   (canonical)
        └── scripts/talks.py --tex ─▶ a LaTeX itemize for the CV

Most entries are structured (year, date, title, venue); a few heterogeneous
ones keep the CV line verbatim in `text`. Fields may contain LaTeX (math in
titles, \\href in venues), so they are emitted verbatim — not escaped.

An optional `slides` URL renders as a trailing ", \\href{url}{slides}." on the
CV line. The website /slides/ page (scripts/slides.py) uses further optional
fields the CV ignores (`video`, `note`), and `web_only: true` entries are shown
on /slides/ but skipped here.

    python3 scripts/talks.py --tex cv/sections/talks_generated.tex
    add --check to compare against an existing file instead of writing.
"""
import argparse
import os
import sys

import yaml

DATA = '_data/talks.yml'
HEADER = '% GENERATED by scripts/talks.py from ' + DATA + ' -- do not edit.\n'


def reconstruct(e):
    if 'title' not in e:
        return e['text']
    venue = e['venue']
    if e.get('slides'):
        # Drop a trailing '.' so a venue like "..., online." doesn't render as
        # "online., \href{}{slides}." — the slides clause supplies the period.
        return (f"{e['year']}, {e['date']}, {{\\emph{{{e['title']}}}}}, "
                f"{venue.rstrip('.')}, \\href{{{e['slides']}}}{{slides}}.")
    return f"{e['year']}, {e['date']}, {{\\emph{{{e['title']}}}}}, {venue}"


def to_tex(entries):
    # `web_only` entries appear on the website /slides/ page but not in the CV.
    cv = [e for e in entries if not e.get('web_only')]
    items = '\n'.join('\\item\n' + reconstruct(e) for e in cv)
    return HEADER + '\\begin{itemize}\n' + items + '\n\\end{itemize}\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--tex', default='-')
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    entries = yaml.safe_load(open(DATA, encoding='utf-8'))
    out = to_tex(entries)

    if a.check:
        cur = open(a.tex, encoding='utf-8').read() if os.path.exists(a.tex) else None
        if cur == out:
            print(f'OK: {a.tex} is up to date with {DATA}')
            return 0
        sys.stderr.write(f'ERROR: {a.tex} is stale; regenerate with '
                         f'scripts/talks.py --tex {a.tex}\n')
        return 1

    if a.tex == '-':
        sys.stdout.write(out)
    else:
        with open(a.tex, 'w', encoding='utf-8') as fh:
            fh.write(out)
        print(f'Wrote {a.tex} ({len(entries)} talks)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
