#!/usr/bin/env python3
"""Generate the CV's Teaching institution tables from _data/teaching.yml.

    python3 scripts/teaching.py --tex cv/sections/teaching_generated.tex
    python3 scripts/teaching.py --check      # verify the .tex is in sync

The data is a list of institutions, each with an ordered list of courses:

    - institution: Warwick
      courses:
        - {period: "2026-27, Term 1", course: "MA4N1 Theorem Proving with Lean"}
        - ...

`period` and `course` are emitted verbatim into a two-column tabular, so they
may contain LaTeX. One source, rendered into the CV; see scripts/README.md.
"""
import argparse
import sys

import yaml

DATA = '_data/teaching.yml'
HEADER = '% GENERATED by scripts/teaching.py from ' + DATA + ' -- do not edit.\n'
COLSPEC = '{@{\\textendash \\hspace{3pt}}l@{ -- }l}'


def render_institution(inst):
    rows = []
    courses = inst['courses']
    for i, c in enumerate(courses):
        last = i == len(courses) - 1
        suffix = '' if last else ' \\\\'
        rows.append(f"{c['period']} &\n{c['course']}{suffix}")
    body = '\n'.join(rows)
    return (
        '\\item\n'
        f"{{\\textbf{{{inst['institution']}}}}}\\\\[3pt]\n"
        f"\\begin{{tabular}}{COLSPEC}\n"
        f"{body}\n"
        '\\end{tabular}'
    )


def to_tex(data):
    items = '\n'.join(render_institution(inst) for inst in data)
    return HEADER + '\\begin{itemize}\n' + items + '\n\\end{itemize}\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--tex', help='write the generated .tex to this path')
    ap.add_argument('--check', action='store_true',
                    help='verify --tex target is in sync (exit 1 if not)')
    args = ap.parse_args()

    data = yaml.safe_load(open(DATA, encoding='utf-8'))
    tex = to_tex(data)

    if args.check:
        if not args.tex:
            ap.error('--check requires --tex')
        current = open(args.tex, encoding='utf-8').read()
        if current != tex:
            print(f'OUT OF SYNC: {args.tex} does not match {DATA}', file=sys.stderr)
            sys.exit(1)
        print(f'{args.tex} is up to date with {DATA}')
        return

    if args.tex:
        with open(args.tex, 'w', encoding='utf-8') as f:
            f.write(tex)
        print(f'wrote {args.tex} ({len(data)} institutions)')
    else:
        sys.stdout.write(tex)


if __name__ == '__main__':
    main()
